Models/ErrorViewModel.cs
namespace SistemaFornecedores.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FornecedorModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaFornecedores.Models
{
    public class FornecedorModel
    {
        public int Id { get; set; }
        [MaxLength(100)]
        [Required(ErrorMessage = "o campo 'nome' é obrigatório")] 
        public string Name { get; set; }
        [MaxLength(14)]
        [Required(ErrorMessage = "o campo 'CNPJ' é obrigatório")]
        public string CNPJ { get; set; }
        public string Especialidade { get; set; }
        [MaxLength(8)]
        [Required(ErrorMessage = "o campo 'CEP' é obrigatório")]
        public string CEP { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Endereco
        {
            get
            {
                return $"{Rua}, {Bairro}, {Cidade}, {UF}";
            }
            set { }
        }

    }
}

Controllers/FornecedorController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaFornecedores.Models;
using SistemaFornecedores.Repositorio;

namespace SistemaFornecedores.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly IFornecedorRepository _fornecedorRepository;
        public FornecedorController(IFornecedorRepository fornecedorRepository)
        {
            _fornecedorRepository = fornecedorRepository;
        }
        public IActionResult Index()
        {
            List<FornecedorModel> fornecedores = _fornecedorRepository.GetAll();
            return View(fornecedores);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {

            FornecedorModel fornecedor = _fornecedorRepository.ListarPorId(id);

            if (fornecedor == null)
            {
                return NotFound("Fornecedor não encontrado.");
            }

            return View(fornecedor);
        }


        public IActionResult ApagarConfirmacao(int id)
        {
            FornecedorModel fornecedor = _fornecedorRepository.ListarPorId(id);

            if (fornecedor == null)
            {
                return NotFound();
            }

            return View(fornecedor);
        }


        [HttpPost]
        public IActionResult Criar(FornecedorModel fornecedor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _fornecedorRepository.Adicionar(fornecedor);
                    TempData["MensagemSucesso"] = "Fornecedor cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View(fornecedor);
            }
            catch (System.Exception error)
            {
                TempData["MensagemErro"] = $"Não foi possível cadasrar o fornecedor, detalhe do erro: {error.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(FornecedorModel fornecedor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _fornecedorRepository.Atualizar(fornecedor);
                    TempData["MensagemSucesso"] = "Fornecedor alterado com sucesso!";
                    return RedirectToAction("Index");
                }
                return View("Editar", fornecedor);
            }
            catch (System.Exception error)
            {
                TempData["MensagemErro"] = $"Não foi possível alterar o fornecedor, detalhe do erro: {error.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult Deletar(int id)
        {
            try
            {
                bool apagado = _fornecedorRepository.Deletar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Fornecedor apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível apagar o fornecedor";
                }

                return RedirectToAction("Index");
            }
            catch (System.Exception error)
            {
                TempData["MensagemErro"] = $"Não foi possível apagar o fornecedor, mais detalhes do erro: {error.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaFornecedores.Models;
using System.Diagnostics;

namespace SistemaFornecedores.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Fornecedor/ApagarConfirmacao.cshtml
@model FornecedorModel
@{
    ViewData["Title"] = "Confirmação apagar fornecedor";
}

<div class="text-center">
    <h3>Realmente deseja apagar o fornecedor @Model.Name ?</h3>
</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Fornecedor" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Fornecedor" asp-route-id="@Model.Id" asp-action="Deletar">Confirmar exclusão</a>

Views/Fornecedor/Criar.cshtml
@model FornecedorModel

@{
    ViewData["Title"] = "Cadastro de Fornecedor";
}

<style>
    .form-group {
        margin-bottom: 10px;
    }
</style>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8="
        crossorigin="anonymous"></script>

<script>

    $(document).ready(function () {

        function limpa_formulário_cep() {
            // Limpa valores do formulário de cep.
            $("#rua").val("");
            $("#bairro").val("");
            $("#cidade").val("");
            $("#uf").val("");
            $("#ibge").val("");
        }

        //Quando o campo cep perde o foco.
        $("#cep").blur(function () {

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            //Verifica se campo cep possui valor informado.
            if (cep != "") {

                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if (validacep.test(cep)) {

                    //Preenche os campos com "..." enquanto consulta webservice.
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    $("#ibge").val("...");

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#rua").val(dados.logradouro);
                            $("#bairro").val(dados.bairro);
                            $("#cidade").val(dados.localidade);
                            $("#uf").val(dados.uf);
                            $("#ibge").val(dados.ibge);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpa_formulário_cep();
            }
        });
    });

</script>

<div class="text-center">
    <h1 class="display-4">Cadastrar Fornecedor</h1>
</div>

<form asp-controller="Fornecedor" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="exampleInputName">Nome</label>
        <input type="text" class="form-control" asp-for="Name" id="exampleInputName" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group">
        <label for="inputCNPJ">CNPJ</label>
        <input type="text" asp-for="CNPJ" class="form-control" id="inputCNPJ" placeholder="CNPJ">
        @Html.ValidationMessageFor(x => x.CNPJ)
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Especialidade</label>
        <select asp-for="Especialidade" class="form-control" id="exampleFormControlSelect1">
            <option>Comércio</option>
            <option>Serviço</option>
            <option>Indústria</option>
        </select>
    </div>
    <div class="form-group">
        <label for="cep">
            CEP:
            <input name="cep" asp-for="CEP" type="text" id="cep" value="" maxlength="9" class="form-control" placeholder="CEP" />
            @Html.ValidationMessageFor(x => x.CEP)
        </label>
    </div>

    <div class="form-group">
        <label for="rua">
            Rua:
            <input asp-for="Rua" name="rua" type="text" id="rua" placeholder="Rua" class="form-control" />
        </label>
    </div>
    <div class="form-group">
        <label for="bairro">
            Bairro:
            <input asp-for="Bairro" name="bairro" type="text" placeholder="Bairro" id="bairro" class="form-control" />
        </label>
    </div>
    <div class="form-group">
        <label for="cidade">
            Cidade:
            <input asp-for="Cidade" name="cidade" type="text" placeholder="Cidade" id="cidade" class="form-control" />
        </label>
    </div>
    <div class="form-group">
        <label for="uf">
            Estado:
            <input asp-for="UF" placeholder="UF" name="uf" type="text" id="uf" class="form-control" />
        </label>
    </div>

    <button type="submit" class="btn btn-primary">Cadastrar</button>
    <a class="btn btn-secondary" asp-controller="Fornecedor" asp-action="Index" role="button">Voltar</a>
</form>

Views/Fornecedor/Editar.cshtml
@model FornecedorModel
@{
    ViewData["Title"] = "Editar Fornecedor";
}

<style>
    .form-group {
        margin-bottom: 10px;
    }
</style>

<div class="text-center">
    <h1 class="display-4">Editar Fornecedor</h1>
</div>

<form asp-controller="Fornecedor" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="exampleInputName">Nome</label>
        <input type="text" class="form-control" asp-for="Name" id="exampleInputName" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group">
        <label for="inputCNPJ">CNPJ</label>
        <input type="text" asp-for="CNPJ" class="form-control" id="inputCNPJ" placeholder="CNPJ">
        @Html.ValidationMessageFor(x => x.CNPJ)
    </div>
    <div class="form-group">
        <label for="exampleFormControlSelect1">Especialidade</label>
        <select asp-for="Especialidade" class="form-control" id="exampleFormControlSelect1">
            <option>Comércio</option>
            <option>Serviço</option>
            <option>Indústria</option>
        </select>
    </div>
    <div class="form-group">
        <label for="cep">
            CEP:
            <input name="cep" asp-for="CEP" type="text" id="cep" maxlength="9" class="form-control" placeholder="CEP" />
            @Html.ValidationMessageFor(x => x.CEP)
        </label>
    </div>

    <div class="form-group">
        <label for="rua">
            Rua:
            <input asp-for="Rua" name="rua" type="text" id="rua" placeholder="Rua" class="form-control" />
        </label>
    </div>
    <div class="form-group">
        <label for="bairro">
            Bairro:
            <input asp-for="Bairro" name="bairro" type="text" placeholder="Bairro" id="bairro" class="form-control" />
        </label>
    </div>
    <div class="form-group">
        <label for="cidade">
            Cidade:
            <input asp-for="Cidade" name="cidade" type="text" placeholder="Cidade" id="cidade" class="form-control" />
        </label>
    </div>
    <div class="form-group">
        <label for="uf">
            Estado:
            <input asp-for="UF" placeholder="UF" name="uf" type="text" id="uf" class="form-control" />
        </label>
    </div>

    <button type="submit" class="btn btn-primary">Cadastrar</button>
    <a class="btn btn-secondary" asp-controller="Fornecedor" asp-action="Index" role="button">Voltar</a>
</form>

Views/Fornecedor/Index.cshtml
@model List<FornecedorModel>
@{
    ViewData["Title"] = "Listagem de fornecedores";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Fornecedor" asp-action="Criar">Adicionar novo fornecedor</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
           @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

<h1 class="display-4">Listagem de fornecedores</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">CNPJ</th>
            <th scope="col">Especialidade</th>
            <th scope="col">CEP</th>
            <th scope="col">Endereço</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
            @if(Model != null && Model.Any())
            {
                foreach (var fornecedor in Model)
                {
                    <tr>
                        <th scope="row">@fornecedor.Id</th>
                        <td>@fornecedor.Name</td>
                        <td>@fornecedor.CNPJ</td>
                        <td>@fornecedor.Especialidade</td>
                        <td>@fornecedor.CEP</td>
                        <td>@fornecedor.Endereco</td>
                        <td>
                            <a role="button" class="btn btn-primary" asp-controller="Fornecedor" asp-action="Editar" asp-route-id="@fornecedor.Id">Editar</a>
                            <a role="button" class="btn btn-danger" asp-controller="Fornecedor" asp-action="ApagarConfirmacao" asp-route-id="@fornecedor.Id">Deletar</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
</table>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Sistema de controle de Fornecedores</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Fornecedores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaFornecedores.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Fornecedores</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedor" asp-action="Index">Fornecedores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Controle de Fornecedores -
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>